site_name: ScaleNPU Documentation
repo_name: OpenCEHardware/ScaleNPU
repo_url: https://github.com/OpenCEHardware/ScaleNPU
extra_css:
  - css/extra.css 
theme:
  name: material
  custom_dir: docs/overrides
  logo: assets/CElogo.png
  favicon: assets/CElogo.png
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - header.autohide
    - navigation.footer
  language: en
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: green

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: green
plugins:
  - search
  - print-site:
      path_to_pdf: "assets/Hardware Documentation Template.pdf"

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html
  - markdown_include.include:
        base_path: docs

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - ScaleNPU:
    - Revisions: block/revisions.md
    - Document Conventions: block/conventions.md
    - Introduction: block/introduction.md
    - Diagrams: block/diagram.md
    - Configuration: block/configuration.md
    - Protocols: block/protocols.md
    - Memory Map: block/memory.md
    - Registers: block/registers.md
    - Clock Domains: block/clocks.md
    - Reset Domains: block/resets.md
    - Interrupts: block/interrupts.md
    - Arbitration: block/arbitration.md
    - Debugging: block/debugging.md
    - Synthesis: block/synthesis.md
    - Verification: block/verification.md
    - Microarchitecture: 
      - Preamble: block/microarchitecture/preamble.md
      - MAC: block/microarchitecture/mac.md
      - Fifo: block/microarchitecture/fifo.md
      - Gatekeeper: block/microarchitecture/gatekeeper.md
      - Systolic Array: block/microarchitecture/systolic.md
      - Matrix Multiplication Unit: block/microarchitecture/mm_unit.md
      - Accumulator: block/microarchitecture/accumulator.md
      - Activation: block/microarchitecture/activation.md
      - Inference: block/microarchitecture/inference.md
      - Memory Ordering: block/microarchitecture/memory_ordering.md
      - Memory Inteface: block/microarchitecture/memory_interface.md
      - Executive: block/microarchitecture/executive.md
  - About: about.md
copyright: |
  &copy; 2024 <a href="https://github.com/OpenCEHardware"  target="_blank" rel="noopener">OpenCEHardware</a>