# TCL File Generated by Component Editor 23.1
# Tue Oct 15 22:58:34 CST 2024
# DO NOT MODIFY


# 
# hs_npu "ScaleNPU" v1.0
#  2024.10.15.22:58:34
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hs_npu
# 
set_module_property DESCRIPTION ""
set_module_property NAME hs_npu
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME ScaleNPU
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL hs_npu_top_flat
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false

# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk_npu clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clk
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rst_n reset_n Input 1


# 
# connection point interrupt
# 
add_interface interrupt interrupt end
set_interface_property interrupt associatedAddressablePoint ""
set_interface_property interrupt associatedClock clk
set_interface_property interrupt bridgedReceiverOffset ""
set_interface_property interrupt bridgesToReceiver ""
set_interface_property interrupt ENABLED true
set_interface_property interrupt EXPORT_OF ""
set_interface_property interrupt PORT_NAME_MAP ""
set_interface_property interrupt CMSIS_SVD_VARIABLES ""
set_interface_property interrupt SVD_ADDRESS_GROUP ""

add_interface_port interrupt irq irq Output 1


# 
# connection point csr
# 
add_interface csr axi4lite end
set_interface_property csr associatedClock clk
set_interface_property csr associatedReset reset
set_interface_property csr readAcceptanceCapability 1
set_interface_property csr writeAcceptanceCapability 1
set_interface_property csr combinedAcceptanceCapability 1
set_interface_property csr readDataReorderingDepth 1
set_interface_property csr bridgesToMaster ""
set_interface_property csr ENABLED true
set_interface_property csr EXPORT_OF ""
set_interface_property csr PORT_NAME_MAP ""
set_interface_property csr CMSIS_SVD_VARIABLES ""
set_interface_property csr SVD_ADDRESS_GROUP ""

add_interface_port csr csr_araddr araddr Input 16
add_interface_port csr csr_arprot arprot Input 3
add_interface_port csr csr_arready arready Output 1
add_interface_port csr csr_arvalid arvalid Input 1
add_interface_port csr csr_awaddr awaddr Input 16
add_interface_port csr csr_awprot awprot Input 3
add_interface_port csr csr_awready awready Output 1
add_interface_port csr csr_awvalid awvalid Input 1
add_interface_port csr csr_bready bready Input 1
add_interface_port csr csr_bresp bresp Output 2
add_interface_port csr csr_bvalid bvalid Output 1
add_interface_port csr csr_rdata rdata Output 32
add_interface_port csr csr_rready rready Input 1
add_interface_port csr csr_rresp rresp Output 2
add_interface_port csr csr_rvalid rvalid Output 1
add_interface_port csr csr_wdata wdata Input 32
add_interface_port csr csr_wready wready Output 1
add_interface_port csr csr_wstrb wstrb Input 4
add_interface_port csr csr_wvalid wvalid Input 1


# 
# connection point mem
# 
add_interface mem axi4 start
set_interface_property mem associatedClock clk
set_interface_property mem associatedReset reset
set_interface_property mem readIssuingCapability 1
set_interface_property mem writeIssuingCapability 1
set_interface_property mem combinedIssuingCapability 1
set_interface_property mem ENABLED true
set_interface_property mem EXPORT_OF ""
set_interface_property mem PORT_NAME_MAP ""
set_interface_property mem CMSIS_SVD_VARIABLES ""
set_interface_property mem SVD_ADDRESS_GROUP ""

add_interface_port mem mem_araddr araddr Output 32
add_interface_port mem mem_arburst arburst Output 2
add_interface_port mem mem_arid arid Output 8
add_interface_port mem mem_arlen arlen Output 8
add_interface_port mem mem_arready arready Input 1
add_interface_port mem mem_arvalid arvalid Output 1
add_interface_port mem mem_awaddr awaddr Output 32
add_interface_port mem mem_awready awready Input 1
add_interface_port mem mem_arsize arsize Output 3
add_interface_port mem mem_awburst awburst Output 2
add_interface_port mem mem_awlen awlen Output 8
add_interface_port mem mem_awsize awsize Output 3
add_interface_port mem mem_bready bready Output 1
add_interface_port mem mem_bvalid bvalid Input 1
add_interface_port mem mem_bresp bresp Input 2
add_interface_port mem mem_rready rready Output 1
add_interface_port mem mem_wvalid wvalid Output 1
add_interface_port mem mem_wdata wdata Output 32
add_interface_port mem mem_rdata rdata Input 32
add_interface_port mem mem_awvalid awvalid Output 1
add_interface_port mem mem_wlast wlast Output 1
add_interface_port mem mem_wready wready Input 1
add_interface_port mem mem_arprot arprot Output 3
add_interface_port mem mem_awprot awprot Output 3
add_interface_port mem mem_rvalid rvalid Input 1
add_interface_port mem mem_bid bid Input 8
add_interface_port mem mem_rid rid Input 8
add_interface_port mem mem_wstrb wstrb Output 4
add_interface_port mem mem_rlast rlast Input 1
add_interface_port mem mem_rresp rresp Input 2
add_interface_port mem mem_awid awid Output 8

